=== mahmoud-elbasiony/XML/lab03/schema.xsd
<!DOCTYPE xml>
<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="buildingNumber"/>
				<xs:element ref="city"/>
				<xs:element ref="region"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="buildingNumber">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="20"/>
				<xs:enumeration value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Damanhour"/>
				<xs:enumeration value="sidi besher"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phone"/>
				<xs:element ref="address"/>
			</xs:sequence>
			<xs:attribute name="email" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ahmed@gmail.com"/>
						<xs:enumeration value="mahmoud@gmail.com"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ahmed"/>
				<xs:enumeration value="mahmoud"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="work"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="alexandria"/>
				<xs:enumeration value="elbehaira"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=""/>
				<xs:enumeration value="abd elsalam elshazy st."/>
				<xs:enumeration value="asdasdasdasd"/>
				<xs:enumeration value="mostafa kamel."/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:int">
			<xs:enumeration value="126546546"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mahmoud-elbasiony/XML/lab03/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone type="work">0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="ahmed@gmail.com">
		<name>ahmed</name>
		<phone type="home">0126546546</phone>
		<address>
			<street>mostafa kamel.</street>
			<buildingNumber>20</buildingNumber>
			<city>sidi besher</city>
			<region>alexandria</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="ahmed@gmail.com">
		<name>ahmed</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="ahmed@gmail.com">
		<name>ahmed</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street/>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="ahmed@gmail.com">
		<name>ahmed</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street>asdasdasdasd</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee email="mahmoud@gmail.com">
		<name>mahmoud</name>
		<phone>0126546546</phone>
		<address>
			<street>abd elsalam elshazy st.</street>
			<buildingNumber>50</buildingNumber>
			<city>Damanhour</city>
			<region>elbehaira</region>
			<country>Egypt</country>
		</address>
	</employee>
</employees>
